// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/29/2025, 3:38:21 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Volumes/Drive D/One.work/One-Dev-CMS/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/plugins/**/*.{js,ts,mjs}","/Volumes/Drive D/One.work/One-Dev-CMS/composables/**/*.{js,ts,mjs}","/Volumes/Drive D/One.work/One-Dev-CMS/utils/**/*.{js,ts,mjs}","/Volumes/Drive D/One.work/One-Dev-CMS/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["16"] = "/Volumes/Drive D/One.work/One-Dev-CMS/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;