// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/29/2025, 2:13:29 PM
const configMerger = require("/Volumes/Drive D/One.work/One-Dev-CMS/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Volumes/Drive D/One.work/One-Dev-CMS/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/plugins/**/*.{js,ts,mjs}","/Volumes/Drive D/One.work/One-Dev-CMS/composables/**/*.{js,ts,mjs}","/Volumes/Drive D/One.work/One-Dev-CMS/utils/**/*.{js,ts,mjs}","/Volumes/Drive D/One.work/One-Dev-CMS/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Drive D/One.work/One-Dev-CMS/app.config.{js,ts,mjs}"] } }));

module.exports = config
